const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Behaviors.Pin,
		C3.Plugins.Audio,
		C3.Plugins.video,
		C3.Plugins.iframe,
		C3.Plugins.HTMLElement,
		C3.Plugins.Browser,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{Brand_Colour1: 0},
	{Brand_Colour2: 0},
	{Logo: 0},
	{"01_SubTitle": 0},
	{Pic_01: 0},
	{Next_Button: 0},
	{Back_Button: 0},
	{Touch: 0},
	{Keyboard: 0},
	{"01_Title": 0},
	{"02_SubTitle": 0},
	{"02_Title": 0},
	{Pic_02: 0},
	{Icon_Mag_Glass: 0},
	{Icon_Report: 0},
	{Icon_Megaphone: 0},
	{"03_SubTitle": 0},
	{"03_Text01": 0},
	{"03_Text2": 0},
	{"03_Text3": 0},
	{"03_Text4": 0},
	{"03_Text5": 0},
	{"03_Text6": 0},
	{"03_Text7": 0},
	{"04_SubTitle": 0},
	{"05_SubTitle": 0},
	{Pic_05: 0},
	{"06_SubTitle": 0},
	{"06_Text1": 0},
	{"06_Text2": 0},
	{"06_Text3": 0},
	{"06_Text4": 0},
	{"06_Text5": 0},
	{"06_Text6": 0},
	{"07_SubTitle": 0},
	{"07_Text": 0},
	{"07_SubTitle2": 0},
	{"07_Text2": 0},
	{"07_Text3": 0},
	{"07_Text4": 0},
	{Icon_Work: 0},
	{Icon_Social_Event: 0},
	{Icon_Social_Connect: 0},
	{Icon_Person: 0},
	{"08_SubTitle": 0},
	{Pic_08: 0},
	{"08_SubTitle2": 0},
	{"08_SubTitle3": 0},
	{"08_SubTitle4": 0},
	{Button1: 0},
	{Pic_09_01: 0},
	{"09_Q1": 0},
	{"09_SubTitle01": 0},
	{"09_SubTitle": 0},
	{"09_Q1_Num": 0},
	{Button2: 0},
	{Button3: 0},
	{Button1_Text: 0},
	{Button2_Text: 0},
	{Button3_Text: 0},
	{Icon_Click: 0},
	{Pin: 0},
	{Icon_Right: 0},
	{Icon_Wrong: 0},
	{Info_Box: 0},
	{Close_Button1: 0},
	{"09_Incorrect_Title": 0},
	{Button4: 0},
	{Button5: 0},
	{"09_Correct_Title": 0},
	{Audio: 0},
	{"09_Q2_Num": 0},
	{"09_Q2": 0},
	{Q2Button1: 0},
	{Q2Button2: 0},
	{Q2Button3: 0},
	{Pic_09_02: 0},
	{"09_Q3_Num": 0},
	{"09_Q3": 0},
	{Q3Button1: 0},
	{Q3Button2: 0},
	{Q3Button3: 0},
	{ClickNext: 0},
	{Pic_09_03: 0},
	{"10_SubTitle": 0},
	{"10_Title": 0},
	{"10Next_Button": 0},
	{"10_SubTitle2": 0},
	{"11Next_Button": 0},
	{"11_Title": 0},
	{"11_SubTitle": 0},
	{"11_SubTitle2": 0},
	{"11_SubTitle3": 0},
	{"11_SubTitle4": 0},
	{"11Next_Button2": 0},
	{"11Next_Button3": 0},
	{"12_SubTitle": 0},
	{Pic_12_Main: 0},
	{"12_Button1": 0},
	{"12_Button2": 0},
	{"12_Button3": 0},
	{"12_Button4": 0},
	{"12_Button5": 0},
	{"12_Button6": 0},
	{"12_Label1": 0},
	{"12_Label2": 0},
	{"12_Label3": 0},
	{"12_Label4": 0},
	{"12_Label5": 0},
	{"12_Label6": 0},
	{Icon_Home: 0},
	{"12a_Title": 0},
	{Formal_Investigation: 0},
	{"12b_Title": 0},
	{"12b_SubTitle": 0},
	{"12b_SubTitle2": 0},
	{"12b_SubTitle3": 0},
	{"12b_SubTitle4": 0},
	{"12b_SubTitle5": 0},
	{"12b_SubTitle6": 0},
	{"12b_SubTitle7": 0},
	{"12b_SubTitle8": 0},
	{Icon_Serious: 0},
	{Icon_Investigate: 0},
	{Icon_Fair: 0},
	{Icon_Communicate: 0},
	{Icon_Procedure: 0},
	{Icon_Sensitive: 0},
	{"12b_Explainer1": 0},
	{"12b_Explainer2": 0},
	{"12b_Explainer3": 0},
	{"12b_Explainer4": 0},
	{"12b_Explainer5": 0},
	{"12b_Explainer6": 0},
	{"12c_Title": 0},
	{ActionFollowingInvestigation: 0},
	{"12d_Title": 0},
	{"12d_SubTitle": 0},
	{"12d_SubTitle2": 0},
	{Pic_12d: 0},
	{"12e_Title": 0},
	{Video_SH_Witness: 0},
	{"12f_Title": 0},
	{Pic_12f: 0},
	{"12f_SubTitle": 0},
	{"12f_SubTitle2": 0},
	{"12f_SubTitle3": 0},
	{"13_Title": 0},
	{"13_SubTitle": 0},
	{iframe: 0},
	{HTMLElement: 0},
	{"13_Link1": 0},
	{Browser: 0},
	{"13_Link2": 0},
	{"13_Link3": 0},
	{"13_Link4": 0},
	{"13_Link5": 0},
	{"13_Link6": 0},
	{"13_Link7": 0},
	{"13_Link4Extra": 0},
	{"13_Link5Extra": 0},
	{"13_Link6Extra": 0},
	{"13_Link7Extra": 0},
	{icon_info: 0},
	{"13_SubTitle2": 0},
	{"13Next_Button": 0},
	{"13_SubTitle3": 0},
	{"13_SubTitle4": 0},
	{"14_Title": 0},
	{"14_SubTitle": 0},
	{"14_Answers": 0},
	{"14_Blank": 0},
	{"14_Blank2": 0},
	{"14_Blank3": 0},
	{"14_Blank4": 0},
	{"14_Blank5": 0},
	{"14_tick": 0},
	{"14_tick2": 0},
	{"14_tick3": 0},
	{"14_tick4": 0},
	{"14_tick5": 0},
	{Pic_14: 0},
	{"14_Button": 0},
	{"14_Button_Text": 0},
	{"14_Correct_Text": 0},
	{"14_InCorrect_Text": 0},
	{"14_Button_Retry": 0},
	{"14_Button_RetryText": 0},
	{"17Title": 0},
	{"17_Subtitle": 0},
	{"17_Subtitle2": 0},
	{"17_SubtitleP2": 0},
	{"17_SubtitleP3": 0},
	{Icon_ClipBoad: 0},
	{"16_Title": 0},
	{"16_Subtitle": 0},
	{"16_Q1_Num": 0},
	{"16_Q1": 0},
	{"16_Button1": 0},
	{"16_Button2": 0},
	{"16_Subtitle2": 0},
	{"16_Subtitle3": 0},
	{"16_Appropriate": 0},
	{"16_Inappropriate": 0},
	{"16_Button3": 0},
	{"16_Button4": 0},
	{"16_Button5": 0},
	{"16_Button6": 0},
	{"16_Pic01": 0},
	{"16_Pic2": 0},
	{"16_Pic3": 0},
	{"16_Q2_Num": 0},
	{"16_Q3_Num": 0},
	{"16_Q2": 0},
	{"16_Q3": 0},
	{"16_Next_Q_Button": 0},
	{Icon_Right2: 0},
	{"16_Correct_Title": 0},
	{"16_Incorrect_Title": 0},
	{"16_Correct_Title2": 0},
	{"16_Incorrect_Title2": 0},
	{"16_Correct_Title3": 0},
	{"16_Incorrect_Title3": 0},
	{"16_Next_Question": 0},
	{"16_Next_Q_Button2": 0},
	{"3_comicBG": 0},
	{"3_01": 0},
	{"3_02": 0},
	{"3_03": 0},
	{"3_04": 0},
	{"3_05": 0},
	{"3_06": 0},
	{Sprite: 0},
	{"3_07": 0},
	{Pic_04_BG: 0},
	{Pic_04_1: 0},
	{Pic_04_2: 0},
	{Pic_04_3: 0},
	{"06_Pic_BG": 0},
	{"06_Pic_01": 0},
	{"06_Pic_02": 0},
	{"06_Pic_03": 0},
	{"06_Pic_04": 0},
	{"06_Pic_05": 0},
	{"06_Pic_06": 0},
	{"15_Pic_01": 0},
	{Back2: 0},
	{Back1: 0},
	{Back3: 0},
	{Next: 0},
	{"12fNext": 0},
	{"14_01": 0},
	{"14_2": 0},
	{"14_3": 0},
	{"14_4": 0},
	{"14_5": 0}
];

self.InstanceType = {
	Brand_Colour1: class extends self.ISpriteInstance {},
	Brand_Colour2: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	_01_SubTitle: class extends self.ITextInstance {},
	Pic_01: class extends self.ISpriteInstance {},
	Next_Button: class extends self.ISpriteInstance {},
	Back_Button: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	_01_Title: class extends self.ITextInstance {},
	_02_SubTitle: class extends self.ITextInstance {},
	_02_Title: class extends self.ITextInstance {},
	Pic_02: class extends self.ISpriteInstance {},
	Icon_Mag_Glass: class extends self.ISpriteInstance {},
	Icon_Report: class extends self.ISpriteInstance {},
	Icon_Megaphone: class extends self.ISpriteInstance {},
	_03_SubTitle: class extends self.ITextInstance {},
	_03_Text01: class extends self.ITextInstance {},
	_03_Text2: class extends self.ITextInstance {},
	_03_Text3: class extends self.ITextInstance {},
	_03_Text4: class extends self.ITextInstance {},
	_03_Text5: class extends self.ITextInstance {},
	_03_Text6: class extends self.ITextInstance {},
	_03_Text7: class extends self.ITextInstance {},
	_04_SubTitle: class extends self.ITextInstance {},
	_05_SubTitle: class extends self.ITextInstance {},
	Pic_05: class extends self.ISpriteInstance {},
	_06_SubTitle: class extends self.ITextInstance {},
	_06_Text1: class extends self.ITextInstance {},
	_06_Text2: class extends self.ITextInstance {},
	_06_Text3: class extends self.ITextInstance {},
	_06_Text4: class extends self.ITextInstance {},
	_06_Text5: class extends self.ITextInstance {},
	_06_Text6: class extends self.ITextInstance {},
	_07_SubTitle: class extends self.ITextInstance {},
	_07_Text: class extends self.ITextInstance {},
	_07_SubTitle2: class extends self.ITextInstance {},
	_07_Text2: class extends self.ITextInstance {},
	_07_Text3: class extends self.ITextInstance {},
	_07_Text4: class extends self.ITextInstance {},
	Icon_Work: class extends self.ISpriteInstance {},
	Icon_Social_Event: class extends self.ISpriteInstance {},
	Icon_Social_Connect: class extends self.ISpriteInstance {},
	Icon_Person: class extends self.ISpriteInstance {},
	_08_SubTitle: class extends self.ITextInstance {},
	Pic_08: class extends self.ISpriteInstance {},
	_08_SubTitle2: class extends self.ITextInstance {},
	_08_SubTitle3: class extends self.ITextInstance {},
	_08_SubTitle4: class extends self.ITextInstance {},
	Button1: class extends self.ISpriteInstance {},
	Pic_09_01: class extends self.ISpriteInstance {},
	_09_Q1: class extends self.ITextInstance {},
	_09_SubTitle01: class extends self.ITextInstance {},
	_09_SubTitle: class extends self.ITextInstance {},
	_09_Q1_Num: class extends self.ITextInstance {},
	Button2: class extends self.ISpriteInstance {},
	Button3: class extends self.ISpriteInstance {},
	Button1_Text: class extends self.ITextInstance {},
	Button2_Text: class extends self.ITextInstance {},
	Button3_Text: class extends self.ITextInstance {},
	Icon_Click: class extends self.ISpriteInstance {},
	Icon_Right: class extends self.ISpriteInstance {},
	Icon_Wrong: class extends self.ISpriteInstance {},
	Info_Box: class extends self.ISpriteInstance {},
	Close_Button1: class extends self.ISpriteInstance {},
	_09_Incorrect_Title: class extends self.ITextInstance {},
	Button4: class extends self.ISpriteInstance {},
	Button5: class extends self.ISpriteInstance {},
	_09_Correct_Title: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	_09_Q2_Num: class extends self.ITextInstance {},
	_09_Q2: class extends self.ITextInstance {},
	Q2Button1: class extends self.ISpriteInstance {},
	Q2Button2: class extends self.ISpriteInstance {},
	Q2Button3: class extends self.ISpriteInstance {},
	Pic_09_02: class extends self.ISpriteInstance {},
	_09_Q3_Num: class extends self.ITextInstance {},
	_09_Q3: class extends self.ITextInstance {},
	Q3Button1: class extends self.ISpriteInstance {},
	Q3Button2: class extends self.ISpriteInstance {},
	Q3Button3: class extends self.ISpriteInstance {},
	ClickNext: class extends self.ITextInstance {},
	Pic_09_03: class extends self.ISpriteInstance {},
	_10_SubTitle: class extends self.ITextInstance {},
	_10_Title: class extends self.ITextInstance {},
	_10Next_Button: class extends self.ISpriteInstance {},
	_10_SubTitle2: class extends self.ITextInstance {},
	_11Next_Button: class extends self.ISpriteInstance {},
	_11_Title: class extends self.ITextInstance {},
	_11_SubTitle: class extends self.ITextInstance {},
	_11_SubTitle2: class extends self.ITextInstance {},
	_11_SubTitle3: class extends self.ITextInstance {},
	_11_SubTitle4: class extends self.ITextInstance {},
	_11Next_Button2: class extends self.ISpriteInstance {},
	_11Next_Button3: class extends self.ISpriteInstance {},
	_12_SubTitle: class extends self.ITextInstance {},
	Pic_12_Main: class extends self.ISpriteInstance {},
	_12_Button1: class extends self.ISpriteInstance {},
	_12_Button2: class extends self.ISpriteInstance {},
	_12_Button3: class extends self.ISpriteInstance {},
	_12_Button4: class extends self.ISpriteInstance {},
	_12_Button5: class extends self.ISpriteInstance {},
	_12_Button6: class extends self.ISpriteInstance {},
	_12_Label1: class extends self.ITextInstance {},
	_12_Label2: class extends self.ITextInstance {},
	_12_Label3: class extends self.ITextInstance {},
	_12_Label4: class extends self.ITextInstance {},
	_12_Label5: class extends self.ITextInstance {},
	_12_Label6: class extends self.ITextInstance {},
	Icon_Home: class extends self.ISpriteInstance {},
	_12a_Title: class extends self.ITextInstance {},
	Formal_Investigation: class extends self.IWorldInstance {},
	_12b_Title: class extends self.ITextInstance {},
	_12b_SubTitle: class extends self.ITextInstance {},
	_12b_SubTitle2: class extends self.ITextInstance {},
	_12b_SubTitle3: class extends self.ITextInstance {},
	_12b_SubTitle4: class extends self.ITextInstance {},
	_12b_SubTitle5: class extends self.ITextInstance {},
	_12b_SubTitle6: class extends self.ITextInstance {},
	_12b_SubTitle7: class extends self.ITextInstance {},
	_12b_SubTitle8: class extends self.ITextInstance {},
	Icon_Serious: class extends self.ISpriteInstance {},
	Icon_Investigate: class extends self.ISpriteInstance {},
	Icon_Fair: class extends self.ISpriteInstance {},
	Icon_Communicate: class extends self.ISpriteInstance {},
	Icon_Procedure: class extends self.ISpriteInstance {},
	Icon_Sensitive: class extends self.ISpriteInstance {},
	_12b_Explainer1: class extends self.ITextInstance {},
	_12b_Explainer2: class extends self.ITextInstance {},
	_12b_Explainer3: class extends self.ITextInstance {},
	_12b_Explainer4: class extends self.ITextInstance {},
	_12b_Explainer5: class extends self.ITextInstance {},
	_12b_Explainer6: class extends self.ITextInstance {},
	_12c_Title: class extends self.ITextInstance {},
	ActionFollowingInvestigation: class extends self.IWorldInstance {},
	_12d_Title: class extends self.ITextInstance {},
	_12d_SubTitle: class extends self.ITextInstance {},
	_12d_SubTitle2: class extends self.ITextInstance {},
	Pic_12d: class extends self.ISpriteInstance {},
	_12e_Title: class extends self.ITextInstance {},
	Video_SH_Witness: class extends self.IWorldInstance {},
	_12f_Title: class extends self.ITextInstance {},
	Pic_12f: class extends self.ISpriteInstance {},
	_12f_SubTitle: class extends self.ITextInstance {},
	_12f_SubTitle2: class extends self.ITextInstance {},
	_12f_SubTitle3: class extends self.ITextInstance {},
	_13_Title: class extends self.ITextInstance {},
	_13_SubTitle: class extends self.ITextInstance {},
	iframe: class extends self.IIframeInstance {},
	HTMLElement: class extends self.IHTMLElementInstance {},
	_13_Link1: class extends self.ITextInstance {},
	Browser: class extends self.IInstance {},
	_13_Link2: class extends self.ITextInstance {},
	_13_Link3: class extends self.ITextInstance {},
	_13_Link4: class extends self.ITextInstance {},
	_13_Link5: class extends self.ITextInstance {},
	_13_Link6: class extends self.ITextInstance {},
	_13_Link7: class extends self.ITextInstance {},
	_13_Link4Extra: class extends self.ITextInstance {},
	_13_Link5Extra: class extends self.ITextInstance {},
	_13_Link6Extra: class extends self.ITextInstance {},
	_13_Link7Extra: class extends self.ITextInstance {},
	icon_info: class extends self.ISpriteInstance {},
	_13_SubTitle2: class extends self.ITextInstance {},
	_13Next_Button: class extends self.ISpriteInstance {},
	_13_SubTitle3: class extends self.ITextInstance {},
	_13_SubTitle4: class extends self.ITextInstance {},
	_14_Title: class extends self.ITextInstance {},
	_14_SubTitle: class extends self.ITextInstance {},
	_14_Answers: class extends self.ITextInstance {},
	_14_Blank: class extends self.ISpriteInstance {},
	_14_Blank2: class extends self.ISpriteInstance {},
	_14_Blank3: class extends self.ISpriteInstance {},
	_14_Blank4: class extends self.ISpriteInstance {},
	_14_Blank5: class extends self.ISpriteInstance {},
	_14_tick: class extends self.ISpriteInstance {},
	_14_tick2: class extends self.ISpriteInstance {},
	_14_tick3: class extends self.ISpriteInstance {},
	_14_tick4: class extends self.ISpriteInstance {},
	_14_tick5: class extends self.ISpriteInstance {},
	Pic_14: class extends self.ISpriteInstance {},
	_14_Button: class extends self.ISpriteInstance {},
	_14_Button_Text: class extends self.ITextInstance {},
	_14_Correct_Text: class extends self.ITextInstance {},
	_14_InCorrect_Text: class extends self.ITextInstance {},
	_14_Button_Retry: class extends self.ISpriteInstance {},
	_14_Button_RetryText: class extends self.ITextInstance {},
	_17Title: class extends self.ITextInstance {},
	_17_Subtitle: class extends self.ITextInstance {},
	_17_Subtitle2: class extends self.ITextInstance {},
	_17_SubtitleP2: class extends self.ITextInstance {},
	_17_SubtitleP3: class extends self.ITextInstance {},
	Icon_ClipBoad: class extends self.ISpriteInstance {},
	_16_Title: class extends self.ITextInstance {},
	_16_Subtitle: class extends self.ITextInstance {},
	_16_Q1_Num: class extends self.ITextInstance {},
	_16_Q1: class extends self.ITextInstance {},
	_16_Button1: class extends self.ISpriteInstance {},
	_16_Button2: class extends self.ISpriteInstance {},
	_16_Subtitle2: class extends self.ITextInstance {},
	_16_Subtitle3: class extends self.ITextInstance {},
	_16_Appropriate: class extends self.ITextInstance {},
	_16_Inappropriate: class extends self.ITextInstance {},
	_16_Button3: class extends self.ISpriteInstance {},
	_16_Button4: class extends self.ISpriteInstance {},
	_16_Button5: class extends self.ISpriteInstance {},
	_16_Button6: class extends self.ISpriteInstance {},
	_16_Pic01: class extends self.ISpriteInstance {},
	_16_Pic2: class extends self.ISpriteInstance {},
	_16_Pic3: class extends self.ISpriteInstance {},
	_16_Q2_Num: class extends self.ITextInstance {},
	_16_Q3_Num: class extends self.ITextInstance {},
	_16_Q2: class extends self.ITextInstance {},
	_16_Q3: class extends self.ITextInstance {},
	_16_Next_Q_Button: class extends self.ISpriteInstance {},
	Icon_Right2: class extends self.ISpriteInstance {},
	_16_Correct_Title: class extends self.ITextInstance {},
	_16_Incorrect_Title: class extends self.ITextInstance {},
	_16_Correct_Title2: class extends self.ITextInstance {},
	_16_Incorrect_Title2: class extends self.ITextInstance {},
	_16_Correct_Title3: class extends self.ITextInstance {},
	_16_Incorrect_Title3: class extends self.ITextInstance {},
	_16_Next_Question: class extends self.ITextInstance {},
	_16_Next_Q_Button2: class extends self.ISpriteInstance {},
	_3_comicBG: class extends self.ISpriteInstance {},
	_3_01: class extends self.ISpriteInstance {},
	_3_02: class extends self.ISpriteInstance {},
	_3_03: class extends self.ISpriteInstance {},
	_3_04: class extends self.ISpriteInstance {},
	_3_05: class extends self.ISpriteInstance {},
	_3_06: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	_3_07: class extends self.ISpriteInstance {},
	Pic_04_BG: class extends self.ISpriteInstance {},
	Pic_04_1: class extends self.ISpriteInstance {},
	Pic_04_2: class extends self.ISpriteInstance {},
	Pic_04_3: class extends self.ISpriteInstance {},
	_06_Pic_BG: class extends self.ISpriteInstance {},
	_06_Pic_01: class extends self.ISpriteInstance {},
	_06_Pic_02: class extends self.ISpriteInstance {},
	_06_Pic_03: class extends self.ISpriteInstance {},
	_06_Pic_04: class extends self.ISpriteInstance {},
	_06_Pic_05: class extends self.ISpriteInstance {},
	_06_Pic_06: class extends self.ISpriteInstance {},
	_15_Pic_01: class extends self.ISpriteInstance {}
}